# These substitutions allow the end user to override certain values
substitutions:
  name: "tagtuner_ble"
  friendly_name: "TagTuner BLE"

packages:
  # Include all of the core configuration
  core: !include tagtuner-atom-grove-ble.yaml

esphome:
  name: "${name}"
  friendly_name: ${friendly_name}
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  project:
    name: LukaGra.TagTuner
    version: dev

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://luka6000/TagTuner/tagtuner-atom-grove-ble.yaml@main
  import_full_config: true

# Sets up the improv via serial client for Wi-Fi provisioning
improv_serial:
  next_url: https://luka6000.github.io/TagTuner/
