# These substitutions allow the end user to override certain values
substitutions:
  name: "tagtuner"
  friendly_name: "TagTuner"
  d1_mini: d1_mini
  buzpin: D7
  ledpin: D8

esphome:
  name: "${name}"
  friendly_name: ${friendly_name}
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  # hello world
  on_boot:
    priority: -100
    then:
    # - light.turn_on:
    #     id: led1
    #     effect: HelloWorld
    - wait_until:
        condition:
          api.connected:
        timeout: 20s
    - text_sensor.template.publish:
        id: status
        state: "Ready"
    # - light.turn_off: led1

esp8266:
  board: $d1_mini
  framework:
    version: recommended

# To be able to get logs from the device via serial and api.
logger:
  # level: VERBOSE
  # level: DEBUG
  # level: WARN
  level: ERROR
  # logs:
  #   light: WARN
  #   pn532: DEBUG
  #   pn532_i2c: DEBUG

packages:
  core-nfc: github://luka6000/TagTuner/tagtuner-core-nfc.yaml@main
  core-comms: github://luka6000/TagTuner/tagtuner-core-comms.yaml@main
  # core-nfc: !include tagtuner-core-nfc.yaml
  # core-comms: !include tagtuner-core-comms.yaml

i2c:
  id: bus_i2c
  scan: False
  frequency: 100kHz
  timeout: 13ms #to prevent pn532 timeout

output:
  - platform: esp8266_pwm
    pin: $buzpin
    id: buzzer

rtttl:
  output: buzzer
  id: buz

script:
  - id: led_blink
    then:
    - rtttl.play: "write:d=24,o=5,b=100:b,b"
  - id: led_ok
    then:
    - rtttl.play: "success:d=24,o=5,b=100:c,g,b"
  - id: led_success
    then:
    - rtttl.play: "write:d=24,o=5,b=100:b,b"
  - id: led_tagwrite
    then:
    - rtttl.play: "write:d=24,o=5,b=100:b"
